### ISSUE TITLE
群晖自带的docker要怎么弄呢？试了很多次都不行哦 

### ISSUE THREAD

**Issue by MapleRedbean** [thesadboy/x-ui-docker#1]
那个 /tmp /run/lock 什么的是把宿主机的挂在过去吗？

**Comment by MapleRedbean** [comment]
这样是不是只能用SHH创建了呢？

**Comment by thesadboy** [comment]
> 那个 /tmp /run/lock 什么的是把宿主机的挂在过去吗？

对，基础库要求这个挂载

**Comment by thesadboy** [comment]
群晖上倒是没试过，不过这个一般不都是在云服务上装么。。。

**Comment by MapleRedbean** [comment]
> 群晖上倒是没试过，不过这个一般不都是在云服务上装么。。。
话是这么说，不过我如过只是免流的话就不用服务器了。另外我有尝试过把 /tmp /run/lock哪些需要挂载的文件夹拷贝到存储，然后用-v挂载，也是不行。
只接安装了centos再安装原汁原味板的x-ui，还是会报错，查了下说是没有安装什么防火墙，需要启动的话得用
“docker run -itd --name centos --privileged centos /usr/sbin/init”，然后就可以正常使用了。不知道docker板的-xui是不是同样的问题，如过是同样的问题，那么docker的xui也可以用
“docker run -itd --name x-ui--privileged x-ui /usr/sbin/init”启动了，因为是群晖，我完全可以启动了再配置端口。

**Comment by thesadboy** [comment]
> 群晖上倒是没试过，不过这个一般不都是在云服务上装么。。。
> 话是这么说，不过我如过只是免流的话就不用服务器了。另外我有尝试过把 /tmp /run/lock哪些需要挂载的文件夹拷贝到存储，然后用-v挂载，也是不行。
> 只接安装了centos再安装原汁原味板的x-ui，还是会报错，查了下说是没有安装什么防火墙，需要启动的话得用
> “docker run -itd --name centos --privileged centos /usr/sbin/init”，然后就可以正常使用了。不知道docker板的-xui是不是同样的问题，如过是同样的问题，那么docker的xui也可以用
> “docker run -itd --name x-ui--privileged x-ui /usr/sbin/init”启动了，因为是群晖，我完全可以启动了再配置端口。

安装报错的话，应该和防火墙没啥关系。。。如果是防火墙问题，应该是安装之后没法访问，官方版本，暂时需要指定版本安装。。。至少我做镜像的时候是，直接安装会报错

**Comment by MapleRedbean** [comment]
> > 群晖上倒是没试过，不过这个一般不都是在云服务上装么。。。
> > 话是这么说，不过我如过只是免流的话就不用服务器了。另外我有尝试过把 /tmp /run/lock哪些需要挂载的文件夹拷贝到存储，然后用-v挂载，也是不行。
> > 只接安装了centos再安装原汁原味板的x-ui，还是会报错，查了下说是没有安装什么防火墙，需要启动的话得用
> > “docker run -itd --name centos --privileged centos /usr/sbin/init”，然后就可以正常使用了。不知道docker板的-xui是不是同样的问题，如过是同样的问题，那么docker的xui也可以用
> > “docker run -itd --name x-ui--privileged x-ui /usr/sbin/init”启动了，因为是群晖，我完全可以启动了再配置端口。
> 
> 安装报错的话，应该和防火墙没啥关系。。。如果是防火墙问题，应该是安装之后没法访问，官方版本，暂时需要指定版本安装。。。至少我做镜像的时候是，直接安装会报错

算了，我现在是装在centos里了，报错我也给你看下。
2021-08-11 01:57:41	stdout	[0;1;31mExiting PID 1...[0m
2021-08-11 01:57:41	stdout	[[0;1;31m!!!!!![0m] Failed to mount API filesystems.
2021-08-11 01:57:41	stdout	[0;1;31mFailed to mount cgroup at /sys/fs/cgroup/systemd: Permission denied[0m
2021-08-11 01:57:41	stdout	[0;1;31mFailed to mount tmpfs at /run/lock: Permission denied[0m
2021-08-11 01:57:41	stdout	[0;1;31mFailed to mount tmpfs at /run: Permission denied[0m

**Comment by thesadboy** [comment]
> > > 群晖上倒是没试过，不过这个一般不都是在云服务上装么。。。
> > > 话是这么说，不过我如过只是免流的话就不用服务器了。另外我有尝试过把 /tmp /run/lock哪些需要挂载的文件夹拷贝到存储，然后用-v挂载，也是不行。
> > > 只接安装了centos再安装原汁原味板的x-ui，还是会报错，查了下说是没有安装什么防火墙，需要启动的话得用
> > > “docker run -itd --name centos --privileged centos /usr/sbin/init”，然后就可以正常使用了。不知道docker板的-xui是不是同样的问题，如过是同样的问题，那么docker的xui也可以用
> > > “docker run -itd --name x-ui--privileged x-ui /usr/sbin/init”启动了，因为是群晖，我完全可以启动了再配置端口。
> > 
> > 
> > 安装报错的话，应该和防火墙没啥关系。。。如果是防火墙问题，应该是安装之后没法访问，官方版本，暂时需要指定版本安装。。。至少我做镜像的时候是，直接安装会报错
> 
> 算了，我现在是装在centos里了，报错我也给你看下。
> 2021-08-11 01:57:41 stdout �[0;1;31mExiting PID 1...�[0m
> 2021-08-11 01:57:41 stdout [�[0;1;31m!!!!!!�[0m] Failed to mount API filesystems.
> 2021-08-11 01:57:41 stdout �[0;1;31mFailed to mount cgroup at /sys/fs/cgroup/systemd: Permission denied�[0m
> 2021-08-11 01:57:41 stdout �[0;1;31mFailed to mount tmpfs at /run/lock: Permission denied�[0m
> 2021-08-11 01:57:41 stdout �[0;1;31mFailed to mount tmpfs at /run: Permission denied�[0m

参考这个链接配置一下启动参数试试 https://blog.csdn.net/mostone/article/details/99659822

**Comment by MapleRedbean** [comment]
我已经解决了不过看的不是这个，我是套了个centos，直接装xui还是不行，在群晖上

**Comment by thesadboy** [comment]
> 我已经解决了不过看的不是这个，我是套了个centos，直接装xui还是不行，在群晖上

那就没必要装docker版本了，直接装原版的吧
