### ISSUE TITLE
可以在Alpine Linux上运行吗？

### ISSUE THREAD

**Issue by C018** [thesadboy/x-ui-docker#2]
可否写个教程？感谢

**Comment by thesadboy** [comment]
安装docker跑一下试试？

**Comment by C018** [comment]
跑不起来

**Comment by C018** [comment]
平时用tg吗？可以一起聊聊天

**Comment by C018** [comment]
![Uploading Screenshot_20210824_054639.jpg…]()

**Comment by C018** [comment]
好像是因为这个/lib/systemd/systemd

**Comment by thesadboy** [comment]
这个系统是不是arm下运行的？我这个好像只能在x86上。。。

**Comment by C018** [comment]
x86

**Comment by thesadboy** [comment]
参数是按照给定的那些设置的么？一般来说应该没啥问题才对。。。，你的截图看不到

**Comment by C018** [comment]
我已经用
https://github.com/XTLS/alpinelinux-install-xray

**Comment by C018** [comment]
解决了
