### ISSUE TITLE
在unraid上配置不成功。。。。。

### ISSUE THREAD

**Issue by MapleRedbean** [thesadboy/x-ui-docker#3]
有遇到过吗

**Comment by MapleRedbean** [comment]
docker run --restart=always --name x-ui -d --net=br0 --ip=192.168.31.204  -e TZ=Asia/Shanghai -e HOST_OS=Unraid --tmpfs /tmp --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /mnt/user/docker/x-ui/:/etc/x-ui thesadboy/x-ui

**Comment by thesadboy** [comment]
木有在unraid上跑过。。。。

**Comment by MapleRedbean** [comment]
> 木有在unraid上跑过。。。。

enen 。我用了lihaixin/x-ui的，已经可以了
